# Generated by Django 5.0.3 on 2024-03-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(default='abc', max_length=1000)),
                ('nid', models.CharField(max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
